name: Build APK

on:
  push:
    branches:
      - master  # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
      
    - name: Build debug artifact
      run: ./gradlew :android:assembleDebug
